In [15]:
import numpy as np

In [31]:
def generateRandMatrix(x, y):
    return np.random.random((x, y))

def checkMat(A, b):
    if (type(A) != np.ndarray or type(b) != np.ndarray):
        print("Case 1", end = " ") # inputs are not matrices
        return False
    elif (np.size(A, 0) != np.size(b, 0)):
        print("Case 2", end = " ") # row size of A and b should be equal
        return False
    elif (np.size(A, 0) < np.size(A, 1)):
        print("Case 3", end = " ") # row size should be less than column size
        return False
    elif (np.size(b,1) != 1):
        print("Case 4", end = " ") # b should only have 1 column
        return False
    else:
        return True

def REF(MREF):
    M = MREF
    rowCount = len(M)
    colCount = len(M[0])
    print("#rows", rowCount, "#cols", colCount)
    
    pivotRow = 0
    for col in range(rowCount):
        largestRow = pivotRow
        
        # Find the row with highest magnitude
        for row in range(pivotRow + 1, rowCount):
            if (abs(M[row, col]) > abs(M[pivotRow, col])):
                largestRow = row
                
        # Make the highest magnitude row as PIVOT_ROW by SWAP elementary OP      
        if (largestRow != pivotRow):
            M[largestRow], M[pivotRow] = M[pivotRow], M[largestRow]
        
        # Perform elementary row OPs only for non-zero leads
        if (abs(M[pivotRow, col]) != 0):
            for row in range(pivotRow + 1, rowCount):
                # ROW = ROW - ROW * (PIVOT_ROW / LEAD_PIVOT_ELEMENT)
                M[row, col:] -= M[row, col] * (M[pivotRow, col:] / M[pivotRow, col]) 
            
            pivotRow += 1
            
    print("\n\n", M)

In [94]:
rows = 100
cols = 99
A = generateRandMatrix(rows, cols)
b = generateRandMatrix(rows,1)

if (not checkMat(A,b)):
    print("ERR: Invalid Matrices\n\n")
else:
    print("Input A: \n", A, "(", np.size(A, 0), "x", np.size(A, 1), ")", "\n")
    print("Input b: \n", b, "(", np.size(b, 0), "x", np.size(b, 1), ")","\n")
    augMat = np.concatenate((A,b), axis = 1) # concatenate "b" to "A" and get augmented matrix
    print("Augmented Matrix: \n", augMat, "(", np.size(augMat, 0), "x", np.size(augMat, 1), ")", "\n")
    REF(augMat)
    

Input A: 
 [[0.62177857 0.77917736 0.60532253 ... 0.19089363 0.30491703 0.74000183]
 [0.04617928 0.44765664 0.47904161 ... 0.9818145  0.41050324 0.98570857]
 [0.37842188 0.66800954 0.39643834 ... 0.91350849 0.59086057 0.54531302]
 ...
 [0.18268409 0.78520073 0.29461    ... 0.9090324  0.92057735 0.25962353]
 [0.99830043 0.07953307 0.5623563  ... 0.16291228 0.9726288  0.90611803]
 [0.57836686 0.10739189 0.95187    ... 0.38020477 0.79495706 0.54665868]] ( 100 x 99 ) 

Input b: 
 [[0.7485298 ]
 [0.39377108]
 [0.50566996]
 [0.79873101]
 [0.65260031]
 [0.91559558]
 [0.7190431 ]
 [0.02006284]
 [0.911481  ]
 [0.92382754]
 [0.93330205]
 [0.0256888 ]
 [0.82462946]
 [0.44477757]
 [0.73987759]
 [0.07228189]
 [0.1424078 ]
 [0.25960665]
 [0.56561734]
 [0.67291869]
 [0.67042639]
 [0.88519623]
 [0.74769201]
 [0.33081059]
 [0.20660978]
 [0.87582421]
 [0.35484683]
 [0.78903662]
 [0.60292885]
 [0.56095144]
 [0.23407461]
 [0.51768964]
 [0.92899925]
 [0.75577062]
 [0.75341941]
 [0.06314764]
 [0.79772766]
 