In [103]:
import numpy as np
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})

In [107]:
def generateRandMatrix(x, y):
    return np.random.random((x, y))

def checkMat(A, b):
    if (type(A) != np.ndarray or type(b) != np.ndarray):
        print("Case 1", end = " ") # inputs are not matrices
        return False
    elif (np.size(A, 0) != np.size(b, 0)):
        print("Case 2", end = " ") # row size of A and b should be equal
        return False
    elif (np.size(A, 0) < np.size(A, 1)):
        print("Case 3", end = " ") # row size should be less than column size
        return False
    elif (np.size(b,1) != 1):
        print("Case 4", end = " ") # b should only have 1 column
        return False
    else:
        return True

def REF(MREF):
    M = MREF
    rowCount = len(M)
    colCount = len(M[0])
    # print("#rows", rowCount, "#cols", colCount)
    
    pivotRow = 0
    for col in range(colCount):
        largestRow = pivotRow
        
        # Find the row with highest magnitude
        for row in range(pivotRow + 1, rowCount):
            if (abs(M[row, col]) > abs(M[pivotRow, col])):
                largestRow = row
                
        # Make the highest magnitude row as PIVOT_ROW by SWAP elementary OP      
        if (largestRow != pivotRow):
            M[largestRow], M[pivotRow] = M[pivotRow], M[largestRow]
        
        # Perform elementary row OPs only for non-zero leads
        if (abs(M[pivotRow, col]) != 0):
            for row in range(pivotRow + 1, rowCount):
                # Elementary OP => ROW = ROW - ROW * (PIVOT_ROW / LEAD_PIVOT_ELEMENT)
                M[row, col:] -= M[row, col] * (M[pivotRow, col:] / M[pivotRow, col]) 
            
            pivotRow += 1
            
    return M

In [109]:
rows = 500
cols = 300
A = generateRandMatrix(rows, cols)
b = generateRandMatrix(rows,1)

if (not checkMat(A,b)):
    print("ERR: Invalid Matrices\n\n")
else:
    augMat = np.concatenate((A,b), axis = 1) # concatenate "b" to "A" and get augmented matrix
    print("Augmented Matrix: \n", augMat, "(", np.size(augMat, 0), "x", np.size(augMat, 1), ")", "\n")
    matrixREF = REF(augMat)
    print("REF: \n", matrixREF)
    # print("Input A: \n", A, "(", np.size(A, 0), "x", np.size(A, 1), ")", "\n")
    # print("Input b: \n", b, "(", np.size(b, 0), "x", np.size(b, 1), ")","\n")
    

Augmented Matrix: 
 [[0.035 0.714 0.174 ... 0.967 0.425 0.825]
 [0.086 0.651 0.896 ... 0.275 0.461 0.675]
 [0.540 0.849 0.010 ... 0.532 0.360 0.532]
 ...
 [0.167 0.276 0.182 ... 0.284 0.917 0.835]
 [0.659 0.559 0.891 ... 0.949 0.348 0.329]
 [0.235 0.509 0.255 ... 0.524 0.867 0.358]] ( 500 x 301 ) 

REF: 
 [[0.035 0.714 0.174 ... 0.967 0.425 0.825]
 [0.000 -1.079 0.475 ... -2.069 -0.568 -1.323]
 [0.000 0.000 -7.036 ... 5.005 -0.834 0.258]
 ...
 [0.000 0.000 0.000 ... 0.000 0.000 0.000]
 [0.000 0.000 0.000 ... 0.000 0.000 0.000]
 [0.000 0.000 0.000 ... 0.000 0.000 0.000]]
